services:
  mongodb:
    profiles:
      - 'dev'
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=prescriptions'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
  mysql:
    profiles:
      - 'dev'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=cms'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
